// <auto-generated />
using System;
using Colorsin.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace colorsin.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260917161220_LoteUnicoUsuarioOrdenYRecepcionParcial")]
    partial class LoteUnicoUsuarioOrdenYRecepcionParcial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_0900_ai_ci")
                .HasAnnotation("ProductVersion", "9.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Colorsin.Domain.Compras.OrdenCompra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Estado")
                        .HasColumnType("enum('Pendiente','ParcialmenteRecibida','Recibida','Cancelada')")
                        .HasColumnName("estado");

                    b.Property<DateTime?>("Fecha")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("fecha")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("PlazoPagoDias")
                        .HasColumnType("int")
                        .HasColumnName("plazo_pago_dias");

                    b.Property<int>("ProveedorId")
                        .HasColumnType("int")
                        .HasColumnName("proveedor_id");

                    b.Property<int>("SucursalId")
                        .HasColumnType("int")
                        .HasColumnName("sucursal_id");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("Estado")
                        .HasDatabaseName("idx_oc_estado");

                    b.HasIndex("ProveedorId");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("idx_oc_usuario");

                    b.HasIndex("SucursalId", "Fecha")
                        .HasDatabaseName("idx_oc_sucursal_fecha");

                    b.ToTable("ordenes_compra", null, t =>
                        {
                            t.HasCheckConstraint("chk_oc_plazo_pago", "`plazo_pago_dias` IS NULL OR `plazo_pago_dias` >= 0");
                        });
                });

            modelBuilder.Entity("Colorsin.Domain.Compras.OrdenCompraDetalle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("Cantidad")
                        .HasPrecision(14, 4)
                        .HasColumnType("decimal(14,4)")
                        .HasColumnName("cantidad");

                    b.Property<decimal>("CantidadRecibida")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(12, 4)
                        .HasColumnType("decimal(12,4)")
                        .HasDefaultValue(0m)
                        .HasColumnName("cantidad_recibida");

                    b.Property<decimal>("Descuento")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("descuento");

                    b.Property<int>("OrdenCompraId")
                        .HasColumnType("int")
                        .HasColumnName("orden_compra_id");

                    b.Property<decimal?>("PrecioUnitario")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("precio_unitario");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int")
                        .HasColumnName("producto_id");

                    b.Property<int>("UnidadId")
                        .HasColumnType("int")
                        .HasColumnName("unidad_id");

                    b.HasKey("Id");

                    b.HasIndex("OrdenCompraId");

                    b.HasIndex("ProductoId");

                    b.HasIndex("UnidadId");

                    b.ToTable("orden_compra_detalle", null, t =>
                        {
                            t.HasCheckConstraint("chk_ocd_cantidad", "`cantidad` IS NULL OR `cantidad` > 0");

                            t.HasCheckConstraint("chk_ocd_cantidad_recibida", "`cantidad_recibida` >= 0 AND (`cantidad` IS NULL OR `cantidad_recibida` <= `cantidad`)");

                            t.HasCheckConstraint("chk_ocd_descuento", "`descuento` >= 0 AND `descuento` <= 100");

                            t.HasCheckConstraint("chk_ocd_precio", "`precio_unitario` IS NULL OR `precio_unitario` >= 0");
                        });
                });

            modelBuilder.Entity("Colorsin.Domain.Compras.ProductoProveedor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("PrecioReferencia")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("precio_referencia");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int")
                        .HasColumnName("producto_id");

                    b.Property<int>("ProveedorId")
                        .HasColumnType("int")
                        .HasColumnName("proveedor_id");

                    b.HasKey("Id");

                    b.HasIndex("ProveedorId");

                    b.HasIndex("ProductoId", "ProveedorId")
                        .IsUnique()
                        .HasDatabaseName("uq_producto_proveedor");

                    b.ToTable("producto_proveedor", (string)null);
                });

            modelBuilder.Entity("Colorsin.Domain.Compras.Proveedor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Contacto")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("contacto");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nombre");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("telefono");

                    b.HasKey("Id");

                    b.ToTable("proveedores", (string)null);
                });

            modelBuilder.Entity("Colorsin.Domain.Comun.EventoAuditoria", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("accion");

                    b.Property<string>("Detalle")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("detalle");

                    b.Property<DateTime>("Fecha")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("fecha")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Modulo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("modulo");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("idx_auditoria_usuario");

                    b.HasIndex("Modulo", "Fecha")
                        .HasDatabaseName("idx_auditoria_modulo_fecha");

                    b.ToTable("auditoria_eventos", (string)null);
                });

            modelBuilder.Entity("Colorsin.Domain.Comun.Sucursal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ciudad")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("ciudad");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Direccion")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("direccion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nombre");

                    b.Property<string>("RolRed")
                        .IsRequired()
                        .HasColumnType("enum('Matriz','Sucursal')")
                        .HasColumnName("rol_red");

                    b.HasKey("Id");

                    b.ToTable("sucursales", (string)null);
                });

            modelBuilder.Entity("Colorsin.Domain.Comun.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nombre");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("enum('Administrador General','Gerente de Sucursal','Operador')")
                        .HasColumnName("rol");

                    b.Property<int?>("SucursalId")
                        .HasColumnType("int")
                        .HasColumnName("sucursal_id");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("uq_usuarios_email");

                    b.HasIndex("SucursalId");

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("Colorsin.Domain.Inventario.InventarioSucursal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CantidadBase")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(14, 4)
                        .HasColumnType("decimal(14,4)")
                        .HasDefaultValue(0m)
                        .HasColumnName("cantidad_base");

                    b.Property<decimal>("CostoPromedio")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(14, 4)
                        .HasColumnType("decimal(14,4)")
                        .HasDefaultValue(0m)
                        .HasColumnName("costo_promedio");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int")
                        .HasColumnName("producto_id");

                    b.Property<decimal>("StockMinimo")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(14, 4)
                        .HasColumnType("decimal(14,4)")
                        .HasDefaultValue(0m)
                        .HasColumnName("stock_minimo");

                    b.Property<int>("SucursalId")
                        .HasColumnType("int")
                        .HasColumnName("sucursal_id");

                    b.HasKey("Id");

                    b.HasIndex("ProductoId");

                    b.HasIndex("SucursalId", "ProductoId")
                        .IsUnique()
                        .HasDatabaseName("uq_inventario_sucursal_producto");

                    b.ToTable("inventario_sucursal", (string)null);
                });

            modelBuilder.Entity("Colorsin.Domain.Inventario.Lote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("CantidadBase")
                        .HasPrecision(14, 4)
                        .HasColumnType("decimal(14,4)")
                        .HasColumnName("cantidad_base");

                    b.Property<DateTime?>("FechaIngreso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_ingreso")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateOnly?>("FechaVencimiento")
                        .HasColumnType("date")
                        .HasColumnName("fecha_vencimiento");

                    b.Property<string>("NumeroLote")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("numero_lote");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int")
                        .HasColumnName("producto_id");

                    b.Property<int>("SucursalId")
                        .HasColumnType("int")
                        .HasColumnName("sucursal_id");

                    b.HasKey("Id");

                    b.HasIndex("FechaVencimiento")
                        .HasDatabaseName("idx_lotes_vencimiento");

                    b.HasIndex("NumeroLote")
                        .HasDatabaseName("idx_lotes_numero");

                    b.HasIndex("SucursalId");

                    b.HasIndex("ProductoId", "SucursalId", "NumeroLote")
                        .IsUnique()
                        .HasDatabaseName("ux_lotes_producto_sucursal_numero");

                    b.ToTable("lotes", (string)null);
                });

            modelBuilder.Entity("Colorsin.Domain.Inventario.MovimientoInventario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("Cantidad")
                        .HasPrecision(14, 4)
                        .HasColumnType("decimal(14,4)")
                        .HasColumnName("cantidad");

                    b.Property<decimal?>("CantidadBase")
                        .HasPrecision(14, 4)
                        .HasColumnType("decimal(14,4)")
                        .HasColumnName("cantidad_base");

                    b.Property<DateTime?>("Fecha")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("fecha")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("LoteId")
                        .HasColumnType("int")
                        .HasColumnName("lote_id");

                    b.Property<string>("Motivo")
                        .HasColumnType("enum('Compra','Venta','Ajuste','Transferencia','Merma','Devolucion')")
                        .HasColumnName("motivo");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("observaciones");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int")
                        .HasColumnName("producto_id");

                    b.Property<int>("SucursalId")
                        .HasColumnType("int")
                        .HasColumnName("sucursal_id");

                    b.Property<string>("Tipo")
                        .HasColumnType("enum('Ingreso','Retiro')")
                        .HasColumnName("tipo");

                    b.Property<int>("UnidadId")
                        .HasColumnType("int")
                        .HasColumnName("unidad_id");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("LoteId")
                        .HasDatabaseName("idx_movinv_lote");

                    b.HasIndex("ProductoId");

                    b.HasIndex("UnidadId");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("SucursalId", "ProductoId", "Fecha")
                        .HasDatabaseName("idx_movinv_sucursal_producto_fecha");

                    b.ToTable("movimientos_inventario", null, t =>
                        {
                            t.HasCheckConstraint("chk_movinv_cantidad", "`cantidad` IS NULL OR `cantidad` > 0");

                            t.HasCheckConstraint("chk_movinv_cantidad_base", "`cantidad_base` IS NULL OR `cantidad_base` > 0");
                        });
                });

            modelBuilder.Entity("Colorsin.Domain.Inventario.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Categoria")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("categoria");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nombre");

                    b.Property<int?>("UnidadBaseId")
                        .HasColumnType("int")
                        .HasColumnName("unidad_base_id");

                    b.HasKey("Id");

                    b.HasIndex("UnidadBaseId");

                    b.ToTable("productos", (string)null);
                });

            modelBuilder.Entity("Colorsin.Domain.Inventario.UnidadMedida", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("FactorConversionLitros")
                        .HasPrecision(12, 6)
                        .HasColumnType("decimal(12,6)")
                        .HasColumnName("factor_conversion_litros");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nombre");

                    b.Property<string>("Simbolo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("simbolo");

                    b.HasKey("Id");

                    b.ToTable("unidades_medida", (string)null);
                });

            modelBuilder.Entity("Colorsin.Domain.Transferencias.NovedadTransferencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("CantidadAfectada")
                        .HasPrecision(14, 4)
                        .HasColumnType("decimal(14,4)")
                        .HasColumnName("cantidad_afectada");

                    b.Property<DateTime?>("Fecha")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("fecha")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text")
                        .HasColumnName("observaciones");

                    b.Property<string>("Tipo")
                        .HasColumnType("enum('Faltante','Averia','Sobrante','Retraso')")
                        .HasColumnName("tipo");

                    b.Property<int>("TransferenciaId")
                        .HasColumnType("int")
                        .HasColumnName("transferencia_id");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("TransferenciaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("novedades_transferencia", null, t =>
                        {
                            t.HasCheckConstraint("chk_novtransf_cantidad", "`cantidad_afectada` IS NULL OR `cantidad_afectada` >= 0");
                        });
                });

            modelBuilder.Entity("Colorsin.Domain.Transferencias.Transferencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("CantidadRecibida")
                        .HasPrecision(14, 4)
                        .HasColumnType("decimal(14,4)")
                        .HasColumnName("cantidad_recibida");

                    b.Property<decimal?>("CantidadSolicitada")
                        .HasPrecision(14, 4)
                        .HasColumnType("decimal(14,4)")
                        .HasColumnName("cantidad_solicitada");

                    b.Property<string>("Estado")
                        .HasColumnType("enum('Solicitada','EnPreparacion','EnTransito','RecibidaCompleta','RecibidaParcial')")
                        .HasColumnName("estado");

                    b.Property<DateTime?>("FechaEstimadaLlegada")
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_estimada_llegada");

                    b.Property<DateTime?>("FechaSolicitud")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_solicitud")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int")
                        .HasColumnName("producto_id");

                    b.Property<int>("SucursalDestinoId")
                        .HasColumnType("int")
                        .HasColumnName("sucursal_destino_id");

                    b.Property<int>("SucursalOrigenId")
                        .HasColumnType("int")
                        .HasColumnName("sucursal_origen_id");

                    b.Property<int>("TransportadoraId")
                        .HasColumnType("int")
                        .HasColumnName("transportadora_id");

                    b.Property<int>("UnidadId")
                        .HasColumnType("int")
                        .HasColumnName("unidad_id");

                    b.Property<string>("Urgencia")
                        .HasColumnType("enum('Baja','Media','Alta')")
                        .HasColumnName("urgencia");

                    b.HasKey("Id");

                    b.HasIndex("ProductoId");

                    b.HasIndex("SucursalOrigenId");

                    b.HasIndex("TransportadoraId");

                    b.HasIndex("UnidadId");

                    b.HasIndex("SucursalDestinoId", "Estado")
                        .HasDatabaseName("idx_transf_destino_estado");

                    b.ToTable("transferencias", null, t =>
                        {
                            t.HasCheckConstraint("chk_transf_cantidades", "(`cantidad_solicitada` IS NULL OR `cantidad_solicitada` > 0) AND (`cantidad_recibida` IS NULL OR `cantidad_recibida` >= 0)");

                            t.HasCheckConstraint("chk_transf_sedes_distintas", "`sucursal_origen_id` <> `sucursal_destino_id`");
                        });
                });

            modelBuilder.Entity("Colorsin.Domain.Transferencias.Transportadora", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nombre");

                    b.Property<string>("TipoServicio")
                        .IsRequired()
                        .HasColumnType("enum('urgente','estandar')")
                        .HasColumnName("tipo_servicio");

                    b.HasKey("Id");

                    b.ToTable("transportadoras", (string)null);
                });

            modelBuilder.Entity("Colorsin.Domain.Ventas.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Direccion")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("direccion");

                    b.Property<string>("Documento")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("documento");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("RazonSocial")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("razon_social");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("telefono");

                    b.Property<string>("TipoPersona")
                        .IsRequired()
                        .HasColumnType("enum('Natural','Juridica')")
                        .HasColumnName("tipo_persona");

                    b.HasKey("Id");

                    b.HasIndex("Documento")
                        .IsUnique()
                        .HasDatabaseName("uq_clientes_documento");

                    b.ToTable("clientes", (string)null);
                });

            modelBuilder.Entity("Colorsin.Domain.Ventas.Venta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("int")
                        .HasColumnName("cliente_id");

                    b.Property<DateTime?>("Fecha")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("fecha")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("SucursalId")
                        .HasColumnType("int")
                        .HasColumnName("sucursal_id");

                    b.Property<decimal?>("Total")
                        .HasPrecision(14, 2)
                        .HasColumnType("decimal(14,2)")
                        .HasColumnName("total");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("SucursalId", "Fecha")
                        .HasDatabaseName("idx_ventas_sucursal_fecha");

                    b.ToTable("ventas", null, t =>
                        {
                            t.HasCheckConstraint("chk_ventas_total", "`total` IS NULL OR `total` >= 0");
                        });
                });

            modelBuilder.Entity("Colorsin.Domain.Ventas.VentaDetalle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("Cantidad")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("cantidad");

                    b.Property<decimal>("Descuento")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("descuento");

                    b.Property<decimal?>("PrecioUnitario")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("precio_unitario");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int")
                        .HasColumnName("producto_id");

                    b.Property<int>("UnidadId")
                        .HasColumnType("int")
                        .HasColumnName("unidad_id");

                    b.Property<int>("VentaId")
                        .HasColumnType("int")
                        .HasColumnName("venta_id");

                    b.HasKey("Id");

                    b.HasIndex("ProductoId");

                    b.HasIndex("UnidadId");

                    b.HasIndex("VentaId");

                    b.ToTable("venta_detalle", null, t =>
                        {
                            t.HasCheckConstraint("chk_vd_cantidad", "`cantidad` IS NULL OR `cantidad` > 0");

                            t.HasCheckConstraint("chk_vd_descuento", "`descuento` >= 0 AND `descuento` <= 100");

                            t.HasCheckConstraint("chk_vd_precio", "`precio_unitario` IS NULL OR `precio_unitario` >= 0");
                        });
                });

            modelBuilder.Entity("Colorsin.Domain.Compras.OrdenCompra", b =>
                {
                    b.HasOne("Colorsin.Domain.Compras.Proveedor", "Proveedor")
                        .WithMany("OrdenesCompra")
                        .HasForeignKey("ProveedorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_oc_proveedor");

                    b.HasOne("Colorsin.Domain.Comun.Sucursal", "Sucursal")
                        .WithMany("OrdenesCompra")
                        .HasForeignKey("SucursalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_oc_sucursal");

                    b.HasOne("Colorsin.Domain.Comun.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_oc_usuario");

                    b.Navigation("Proveedor");

                    b.Navigation("Sucursal");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Colorsin.Domain.Compras.OrdenCompraDetalle", b =>
                {
                    b.HasOne("Colorsin.Domain.Compras.OrdenCompra", "OrdenCompra")
                        .WithMany("Detalles")
                        .HasForeignKey("OrdenCompraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ocd_orden");

                    b.HasOne("Colorsin.Domain.Inventario.Producto", "Producto")
                        .WithMany("LineasCompra")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_ocd_producto");

                    b.HasOne("Colorsin.Domain.Inventario.UnidadMedida", "Unidad")
                        .WithMany("LineasCompra")
                        .HasForeignKey("UnidadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_ocd_unidad");

                    b.Navigation("OrdenCompra");

                    b.Navigation("Producto");

                    b.Navigation("Unidad");
                });

            modelBuilder.Entity("Colorsin.Domain.Compras.ProductoProveedor", b =>
                {
                    b.HasOne("Colorsin.Domain.Inventario.Producto", "Producto")
                        .WithMany("Proveedores")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_prodprov_producto");

                    b.HasOne("Colorsin.Domain.Compras.Proveedor", "Proveedor")
                        .WithMany("Productos")
                        .HasForeignKey("ProveedorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_prodprov_proveedor");

                    b.Navigation("Producto");

                    b.Navigation("Proveedor");
                });

            modelBuilder.Entity("Colorsin.Domain.Comun.EventoAuditoria", b =>
                {
                    b.HasOne("Colorsin.Domain.Comun.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_auditoria_usuario");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Colorsin.Domain.Comun.Usuario", b =>
                {
                    b.HasOne("Colorsin.Domain.Comun.Sucursal", "Sucursal")
                        .WithMany("Usuarios")
                        .HasForeignKey("SucursalId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_usuarios_sucursal");

                    b.Navigation("Sucursal");
                });

            modelBuilder.Entity("Colorsin.Domain.Inventario.InventarioSucursal", b =>
                {
                    b.HasOne("Colorsin.Domain.Inventario.Producto", "Producto")
                        .WithMany("Inventarios")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_inventario_producto");

                    b.HasOne("Colorsin.Domain.Comun.Sucursal", "Sucursal")
                        .WithMany("Inventarios")
                        .HasForeignKey("SucursalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_inventario_sucursal");

                    b.Navigation("Producto");

                    b.Navigation("Sucursal");
                });

            modelBuilder.Entity("Colorsin.Domain.Inventario.Lote", b =>
                {
                    b.HasOne("Colorsin.Domain.Inventario.Producto", "Producto")
                        .WithMany("Lotes")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_lotes_producto");

                    b.HasOne("Colorsin.Domain.Comun.Sucursal", "Sucursal")
                        .WithMany("Lotes")
                        .HasForeignKey("SucursalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_lotes_sucursal");

                    b.Navigation("Producto");

                    b.Navigation("Sucursal");
                });

            modelBuilder.Entity("Colorsin.Domain.Inventario.MovimientoInventario", b =>
                {
                    b.HasOne("Colorsin.Domain.Inventario.Lote", "Lote")
                        .WithMany()
                        .HasForeignKey("LoteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_movinv_lote");

                    b.HasOne("Colorsin.Domain.Inventario.Producto", "Producto")
                        .WithMany("Movimientos")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_movinv_producto");

                    b.HasOne("Colorsin.Domain.Comun.Sucursal", "Sucursal")
                        .WithMany("Movimientos")
                        .HasForeignKey("SucursalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_movinv_sucursal");

                    b.HasOne("Colorsin.Domain.Inventario.UnidadMedida", "Unidad")
                        .WithMany("Movimientos")
                        .HasForeignKey("UnidadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_movinv_unidad");

                    b.HasOne("Colorsin.Domain.Comun.Usuario", "Usuario")
                        .WithMany("Movimientos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_movinv_usuario");

                    b.Navigation("Lote");

                    b.Navigation("Producto");

                    b.Navigation("Sucursal");

                    b.Navigation("Unidad");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Colorsin.Domain.Inventario.Producto", b =>
                {
                    b.HasOne("Colorsin.Domain.Inventario.UnidadMedida", "UnidadBase")
                        .WithMany("ProductosConUnidadBase")
                        .HasForeignKey("UnidadBaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_productos_unidad_base");

                    b.Navigation("UnidadBase");
                });

            modelBuilder.Entity("Colorsin.Domain.Transferencias.NovedadTransferencia", b =>
                {
                    b.HasOne("Colorsin.Domain.Transferencias.Transferencia", "Transferencia")
                        .WithMany("Novedades")
                        .HasForeignKey("TransferenciaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_novtransf_transferencia");

                    b.HasOne("Colorsin.Domain.Comun.Usuario", "Usuario")
                        .WithMany("NovedadesReportadas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_novtransf_usuario");

                    b.Navigation("Transferencia");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Colorsin.Domain.Transferencias.Transferencia", b =>
                {
                    b.HasOne("Colorsin.Domain.Inventario.Producto", "Producto")
                        .WithMany("Transferencias")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_transf_producto");

                    b.HasOne("Colorsin.Domain.Comun.Sucursal", "SucursalDestino")
                        .WithMany("TransferenciasRecibidas")
                        .HasForeignKey("SucursalDestinoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_transf_sucursal_destino");

                    b.HasOne("Colorsin.Domain.Comun.Sucursal", "SucursalOrigen")
                        .WithMany("TransferenciasEnviadas")
                        .HasForeignKey("SucursalOrigenId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_transf_sucursal_origen");

                    b.HasOne("Colorsin.Domain.Transferencias.Transportadora", "Transportadora")
                        .WithMany("Transferencias")
                        .HasForeignKey("TransportadoraId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_transf_transportadora");

                    b.HasOne("Colorsin.Domain.Inventario.UnidadMedida", "Unidad")
                        .WithMany("Transferencias")
                        .HasForeignKey("UnidadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_transf_unidad");

                    b.Navigation("Producto");

                    b.Navigation("SucursalDestino");

                    b.Navigation("SucursalOrigen");

                    b.Navigation("Transportadora");

                    b.Navigation("Unidad");
                });

            modelBuilder.Entity("Colorsin.Domain.Ventas.Venta", b =>
                {
                    b.HasOne("Colorsin.Domain.Ventas.Cliente", "Cliente")
                        .WithMany("Ventas")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_ventas_cliente");

                    b.HasOne("Colorsin.Domain.Comun.Sucursal", "Sucursal")
                        .WithMany("Ventas")
                        .HasForeignKey("SucursalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_ventas_sucursal");

                    b.HasOne("Colorsin.Domain.Comun.Usuario", "Usuario")
                        .WithMany("Ventas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_ventas_usuario");

                    b.Navigation("Cliente");

                    b.Navigation("Sucursal");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Colorsin.Domain.Ventas.VentaDetalle", b =>
                {
                    b.HasOne("Colorsin.Domain.Inventario.Producto", "Producto")
                        .WithMany("LineasVenta")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_vd_producto");

                    b.HasOne("Colorsin.Domain.Inventario.UnidadMedida", "Unidad")
                        .WithMany("LineasVenta")
                        .HasForeignKey("UnidadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_vd_unidad");

                    b.HasOne("Colorsin.Domain.Ventas.Venta", "Venta")
                        .WithMany("Detalles")
                        .HasForeignKey("VentaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_vd_venta");

                    b.Navigation("Producto");

                    b.Navigation("Unidad");

                    b.Navigation("Venta");
                });

            modelBuilder.Entity("Colorsin.Domain.Compras.OrdenCompra", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("Colorsin.Domain.Compras.Proveedor", b =>
                {
                    b.Navigation("OrdenesCompra");

                    b.Navigation("Productos");
                });

            modelBuilder.Entity("Colorsin.Domain.Comun.Sucursal", b =>
                {
                    b.Navigation("Inventarios");

                    b.Navigation("Lotes");

                    b.Navigation("Movimientos");

                    b.Navigation("OrdenesCompra");

                    b.Navigation("TransferenciasEnviadas");

                    b.Navigation("TransferenciasRecibidas");

                    b.Navigation("Usuarios");

                    b.Navigation("Ventas");
                });

            modelBuilder.Entity("Colorsin.Domain.Comun.Usuario", b =>
                {
                    b.Navigation("Movimientos");

                    b.Navigation("NovedadesReportadas");

                    b.Navigation("Ventas");
                });

            modelBuilder.Entity("Colorsin.Domain.Inventario.Producto", b =>
                {
                    b.Navigation("Inventarios");

                    b.Navigation("LineasCompra");

                    b.Navigation("LineasVenta");

                    b.Navigation("Lotes");

                    b.Navigation("Movimientos");

                    b.Navigation("Proveedores");

                    b.Navigation("Transferencias");
                });

            modelBuilder.Entity("Colorsin.Domain.Inventario.UnidadMedida", b =>
                {
                    b.Navigation("LineasCompra");

                    b.Navigation("LineasVenta");

                    b.Navigation("Movimientos");

                    b.Navigation("ProductosConUnidadBase");

                    b.Navigation("Transferencias");
                });

            modelBuilder.Entity("Colorsin.Domain.Transferencias.Transferencia", b =>
                {
                    b.Navigation("Novedades");
                });

            modelBuilder.Entity("Colorsin.Domain.Transferencias.Transportadora", b =>
                {
                    b.Navigation("Transferencias");
                });

            modelBuilder.Entity("Colorsin.Domain.Ventas.Cliente", b =>
                {
                    b.Navigation("Ventas");
                });

            modelBuilder.Entity("Colorsin.Domain.Ventas.Venta", b =>
                {
                    b.Navigation("Detalles");
                });
#pragma warning restore 612, 618
        }
    }
}
